<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>G. Tabla de frecuencias</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R para economistas</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1_instalacion.html">1 Inst</a>
</li>
<li>
  <a href="2_ventanas.html">2 Introd</a>
</li>
<li>
  <a href="3_funciones_operadores.html">3 Func y oper básic</a>
</li>
<li>
  <a href="4_paquetes.html">4 Paquet</a>
</li>
<li>
  <a href="5_vectores.html">5 Vect</a>
</li>
<li>
  <a href="6_matrices.html">6 Matr</a>
</li>
<li>
  <a href="7_arrays.html">7 Arra</a>
</li>
<li>
  <a href="8_dataframes.html">8 Data Fr</a>
</li>
<li>
  <a href="9_data.html">9 Datos ejem (data)</a>
</li>
<li>
  <a href="10_lectura_escritura.html">10 Lect y escr archi exter</a>
</li>
<li>
  <a href="11_funciones.html">11 Func (function)</a>
</li>
<li>
  <a href="12_aleatorios.html">12 Núme aleat</a>
</li>
<li>
  <a href="Ejercicio_1.html">Eje 1</a>
</li>
<li>
  <a href="Ejercicio_2.html">Eje 2</a>
</li>
<li>
  <a href="A_dispersion.html">A Gráf dispersión</a>
</li>
<li>
  <a href="B_barras.html">B Gráf barra o distrib</a>
</li>
<li>
  <a href="C_histograma.html">C Histog</a>
</li>
<li>
  <a href="D_boxplot.html">D Gráf caja o Boxplot</a>
</li>
<li>
  <a href="E_matrices_dispersion.html">E Matr Gráf Dispers</a>
</li>
<li>
  <a href="F_coeficiente_correlacion.html">F Coef Correl</a>
</li>
<li>
  <a href="G_tabla_frecuencias.html">G Tabl Frec</a>
</li>
<li>
  <a href="H_medidas_posicion_dispersion_forma.html">H Med Pos, Disp, Form</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">G. Tabla de frecuencias</h1>

</div>


<div id="frecuencias-unidimensionales-table-y-prop.table"
class="section level2">
<h2>1. Frecuencias Unidimensionales <code>table</code> y
<code>prop.table</code></h2>
<div id="frecuencias-absoluta-con-table" class="section level3">
<h3>1.1. Frecuencias absoluta con <code>table()</code></h3>
<p>La función <code>table()</code> simplemente <strong>cuenta</strong>
cuántas veces aparece cada valor en tu conjunto (por ejemplo, una
columna de una data) de datos. Es el <strong>conteo
directo</strong>.</p>
<p>Si usamos la columna <code>cyl</code> (cilindros) de los coches en
<code>mtcars</code>:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># Creamos la tabla de conteo </span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>fa <span class="ot">&lt;-</span> <span class="fu">table</span>(mtcars<span class="sc">$</span>cyl)  </span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="co"># Ver el resultado </span></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">print</span>(fa)</span></code></pre></div>
<pre><code>## 
##  4  6  8 
## 11  7 14</code></pre>
<p><strong>¿Qué verás?</strong> R te dirá algo como:</p>
<ul>
<li><p><strong>4</strong>: 11 (Hay 11 coches de 4 cilindros)</p></li>
<li><p><strong>6</strong>: 7 (Hay 7 coches de 6 cilindros)</p></li>
<li><p><strong>8</strong>: 14 (Hay 14 coches de 8 cilindros)</p></li>
</ul>
<div id="frecuencia-relativa-con-prop.table" class="section level4">
<h4>1.2. Frecuencia Relativa con <code>prop.table()</code></h4>
<p>A veces no quieres saber cuántos hay, sino <strong>qué porcentaje del
total</strong> representan. Para eso usamos
<code>prop.table()</code>.</p>
<blockquote>
<p><strong>Ojo aquí: Muy importante:</strong> <code>prop.table()</code>
no se aplica directamente a los datos iniciales, sino a una tabla que ya
hayas creado con <code>table()</code>, en ente caso sobre la tabla
<code>fa</code>.</p>
</blockquote>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># Convertimos la tabla anterior en proporciones (del 0 al 1)</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>proporciones <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(fa)</span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a><span class="fu">print</span>(proporciones)</span></code></pre></div>
<pre><code>## 
##       4       6       8 
## 0.34375 0.21875 0.43750</code></pre>
<p>Se interpreta: el 34.38% de los coches tienen 4 cilindros, el 21.88%
tiene 6 cilindros y el 43.75% tienen 8 cilindros.</p>
</div>
</div>
<div id="ejercicio-1" class="section level3">
<h3>Ejercicio 1:</h3>
<p>Calcula las <strong>Frecuencias Absolutas</strong> y las
<strong>Frecuencias Relativas</strong> de la columna <code>sexo</code>
del archivo de texto <code>empleados.txt</code>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co"># Cargamos el archivo de texto con read.table</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a><span class="co"># Lo guardamos como datos</span></span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> <span class="st">&quot;empleados.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a><span class="co"># Visualizamos los primeros filas</span></span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code></pre></div>
<pre><code>##   id   sexo   fechnac educ         catlab salario salini tiempemp expprev
## 1  1 Hombre  2/3/1952   15      Directivo   57000  27000       98     144
## 2  2 Hombre 5/23/1958   16 Administrativo   40200  18750       98      36
## 3  3  Mujer 7/26/1929   12 Administrativo   21450  12000       98     381
## 4  4  Mujer 4/15/1947    8 Administrativo   21900  13200       98     190
## 5  5 Hombre  2/9/1955   15 Administrativo   45000  21000       98     138
## 6  6 Hombre 8/22/1958   15 Administrativo   32100  13500       98      67
##   minoria
## 1      No
## 2      No
## 3      No
## 4      No
## 5      No
## 6      No</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># Frecuencia absoluta de la columna sexo del archivo empleados.txt</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>tabla1d <span class="ot">&lt;-</span> <span class="fu">table</span>(datos<span class="sc">$</span>sexo)</span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a><span class="co">#Mostramos la tabla1d relativa</span></span>
<span id="cb7-5"><a href="#cb7-5" tabindex="-1"></a>tabla1d</span></code></pre></div>
<pre><code>## 
## Hombre  Mujer 
##    258    216</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="co"># Frecuencia relativa (proporción)</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a><span class="co"># IMPORTANTE: Hay que hacerla tomando como base la tabla de frecuencia absoluta t1d, no desde los datos originales</span></span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" tabindex="-1"></a>tabla1d.relativa <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(tabla1d)</span>
<span id="cb9-5"><a href="#cb9-5" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" tabindex="-1"></a><span class="co">#Mostramos tabla1d.relativa</span></span>
<span id="cb9-7"><a href="#cb9-7" tabindex="-1"></a>tabla1d.relativa</span></code></pre></div>
<pre><code>## 
##    Hombre     Mujer 
## 0.5443038 0.4556962</code></pre>
</div>
</div>
<div id="tablas-bidimensionales-tablas-de-contingencia"
class="section level2">
<h2>2. Tablas Bidimensionales (Tablas de Contingencia)</h2>
<p>Ideales para analizar la relación entre dos variables categóricas.
Las <strong>tablas de contingencia</strong> nos permiten ver si existe
una “amistad” entre dos variables.</p>
<p>Por ejemplo: ¿Los coches con más cilindros suelen ser automáticos o
manuales?</p>
<div id="la-tabla-básica-tablevar1-var2" class="section level3">
<h3>2.1. La tabla básica <code>table(var1, var2)</code></h3>
<p>Para cruzar datos en R, simplemente pasas dos columnas a la función
<code>table()</code>. Usemos <code>cyl</code> (cilindros) y
<code>am</code> (transmisión: 0 = automático, 1 = manual):</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># Creamos la tabla bidimensional con dos columnas cyl y am</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>tabla_bidimen <span class="ot">&lt;-</span> <span class="fu">table</span>(mtcars<span class="sc">$</span>cyl, mtcars<span class="sc">$</span>am)</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a><span class="fu">print</span>(tabla_bidimen)</span></code></pre></div>
<pre><code>##    
##      0  1
##   4  3  8
##   6  4  3
##   8 12  2</code></pre>
<p><strong>Interpretación</strong>: Hay <strong>3 coches</strong> de
<strong>4 cilindros automáticos</strong> <strong>(0)</strong></p>
</div>
<div id="ejercicio-2" class="section level3">
<h3>Ejercicio 2:</h3>
<p>Calcular la <strong>tabla de contingencia o bidimensional</strong> de
las columnas <code>sexo</code> y <code>catlab</code> del archivo de
texto <code>empleados.txt</code></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># Cargamos el archivo</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> <span class="st">&quot;empleados.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a><span class="co"># Visualizamos los primeros filas</span></span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code></pre></div>
<pre><code>##   id   sexo   fechnac educ         catlab salario salini tiempemp expprev
## 1  1 Hombre  2/3/1952   15      Directivo   57000  27000       98     144
## 2  2 Hombre 5/23/1958   16 Administrativo   40200  18750       98      36
## 3  3  Mujer 7/26/1929   12 Administrativo   21450  12000       98     381
## 4  4  Mujer 4/15/1947    8 Administrativo   21900  13200       98     190
## 5  5 Hombre  2/9/1955   15 Administrativo   45000  21000       98     138
## 6  6 Hombre 8/22/1958   15 Administrativo   32100  13500       98      67
##   minoria
## 1      No
## 2      No
## 3      No
## 4      No
## 5      No
## 6      No</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>tab2d <span class="ot">&lt;-</span> <span class="fu">table</span>(datos<span class="sc">$</span>sexo, datos<span class="sc">$</span>catlab)</span></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># Creamos la tabla bidimensional con table(  ,  )</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>tab2d <span class="ot">&lt;-</span> <span class="fu">table</span>(datos<span class="sc">$</span>sexo, datos<span class="sc">$</span>catlab)</span></code></pre></div>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="co"># Proporciones sobre el total de la tabla (todo suma 1)</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a><span class="fu">prop.table</span>(tab2d)</span></code></pre></div>
<pre><code>##         
##          Administrativo  Directivo  Seguridad
##   Hombre     0.33122363 0.15611814 0.05696203
##   Mujer      0.43459916 0.02109705 0.00000000</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a><span class="co"># Porcentajes sobre el total de la tabla</span></span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a><span class="fu">prop.table</span>(tab2d) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>##         
##          Administrativo Directivo Seguridad
##   Hombre      33.122363 15.611814  5.696203
##   Mujer       43.459916  2.109705  0.000000</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="co"># Porcentajes por filas (margen 1)</span></span>
<span id="cb21-2"><a href="#cb21-2" tabindex="-1"></a><span class="fu">prop.table</span>(tab2d, <span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>##         
##          Administrativo Directivo Seguridad
##   Hombre       60.85271  28.68217  10.46512
##   Mujer        95.37037   4.62963   0.00000</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="co"># Porcentajes por columnas (margen 2)</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a><span class="fu">prop.table</span>(tab2d, <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span></span></code></pre></div>
<pre><code>##         
##          Administrativo Directivo Seguridad
##   Hombre       43.25069  88.09524 100.00000
##   Mujer        56.74931  11.90476   0.00000</code></pre>
</div>
</div>
<div id="construcción-de-una-tabla-de-frecuencias-completa"
class="section level2">
<h2>3. Construcción de una Tabla de Frecuencias Completa</h2>
<p>Para <strong>variables cualitativas (numéricas)</strong>, podemos
ensamblar una tabla profesional que incluya <strong>frecuencias
absolutas (</strong><span class="math inline">\(n_i\)</span><strong>),
acumuladas (</strong><span class="math inline">\(N_i\)</span><strong>),
relativas (</strong><span class="math inline">\(f_i\)</span><strong>) y
relativas acumuladas (</strong><span
class="math inline">\(F_i\)</span><strong>).</strong></p>
<p>Ejercicio 3:</p>
<p>Crear la <strong>tabla de frecuencias completa</strong> de la columna
<code>educ</code> del archivo de texto <code>empleados.txt.</code></p>
<p>Aunque ya tenemos el archivo cargado de antes, vamos a cargarlo de
nuevo:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="co"># Cargamos el archivo</span></span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file =</span> <span class="st">&quot;empleados.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a><span class="co"># Visualizamos los primeros filas</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a><span class="fu">head</span>(datos)</span></code></pre></div>
<pre><code>##   id   sexo   fechnac educ         catlab salario salini tiempemp expprev
## 1  1 Hombre  2/3/1952   15      Directivo   57000  27000       98     144
## 2  2 Hombre 5/23/1958   16 Administrativo   40200  18750       98      36
## 3  3  Mujer 7/26/1929   12 Administrativo   21450  12000       98     381
## 4  4  Mujer 4/15/1947    8 Administrativo   21900  13200       98     190
## 5  5 Hombre  2/9/1955   15 Administrativo   45000  21000       98     138
## 6  6 Hombre 8/22/1958   15 Administrativo   32100  13500       98      67
##   minoria
## 1      No
## 2      No
## 3      No
## 4      No
## 5      No
## 6      No</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a>fa   <span class="ot">&lt;-</span> <span class="fu">table</span>(datos<span class="sc">$</span>educ)     <span class="co"># Frecuencia absoluta, con table</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a>fac  <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(fa)            <span class="co"># Frecuencia absoluta acumulada, con cumsum sobre fa</span></span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a>fr   <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(fa)        <span class="co"># Frecuencia relativa, con prop.table</span></span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a>facr <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(fr)            <span class="co"># Frecuencia relativa acumulada, con cunsum sobre fr</span></span>
<span id="cb27-5"><a href="#cb27-5" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" tabindex="-1"></a><span class="co"># Ensamblado en un Data Frame los vectore</span></span>
<span id="cb27-7"><a href="#cb27-7" tabindex="-1"></a>mitabla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(fa, fac, fr, facr)[, <span class="sc">-</span><span class="dv">4</span>]</span>
<span id="cb27-8"><a href="#cb27-8" tabindex="-1"></a><span class="fu">colnames</span>(mitabla) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Categoría educ&quot;</span>, <span class="st">&quot;ni&quot;</span>, <span class="st">&quot;Ni&quot;</span>, <span class="st">&quot;fi&quot;</span>, <span class="st">&quot;Fi&quot;</span>)</span>
<span id="cb27-9"><a href="#cb27-9" tabindex="-1"></a>mitabla</span></code></pre></div>
<pre><code>##    Categoría educ  ni  Ni          fi        Fi
## 8               8  53  53 0.111814346 0.1118143
## 12             12 190 243 0.400843882 0.5126582
## 14             14   6 249 0.012658228 0.5253165
## 15             15 116 365 0.244725738 0.7700422
## 16             16  59 424 0.124472574 0.8945148
## 17             17  11 435 0.023206751 0.9177215
## 18             18   9 444 0.018987342 0.9367089
## 19             19  27 471 0.056962025 0.9936709
## 20             20   2 473 0.004219409 0.9978903
## 21             21   1 474 0.002109705 1.0000000</code></pre>
<div id="un-pequeño-detalle-técnico" class="section level3">
<h3>Un pequeño detalle técnico:</h3>
<p>El comando <strong><code>[, -4]</code></strong> que usaste es muy
inteligente. Cuando haces <code>data.frame(fa, fr...)</code>, R repite
la columna de las categorías porque tanto <code>fa</code> como
<code>fr</code> la llevan consigo. Al poner <code>-4</code>, borras esa
columna repetida para que la tabla quede impecable.</p>
<hr />
</div>
</div>
<div id="agrupación-en-intervalos-variables-numéricas"
class="section level2">
<h2>4. Agrupación en Intervalos (Variables Numéricas)</h2>
<p>Para variables continuas, es necesario convertir valores numéricos en
intervalos categóricos mediante <code>cut()</code>.</p>
<div id="ejemplo-básico" class="section level3">
<h3>Ejemplo básico</h3>
</div>
<div id="qué-hace-cada-parte" class="section level3">
<h3>Qué hace cada parte</h3>
<p>1️⃣ <code>temp</code> → vector de temperaturas.<br />
2️⃣ <code>cut(temp, breaks = c(0, 20, 30, 50))</code> → divide los
valores en <strong>intervalos</strong>:</p>
<ul>
<li><p><code>(0,20]</code> → valores mayores que 0 hasta 20</p></li>
<li><p><code>(20,30]</code> → valores mayores que 20 hasta 30</p></li>
<li><p><code>(30,50]</code> → valores mayores que 30 hasta 50</p></li>
<li><div>
<blockquote>
<p>Nota: por defecto <code>cut()</code> <strong>el intervalo incluye el
límite superior</strong> <code>(a,b]</code>.</p>
</blockquote>
</div></li>
</ul>
<p>3️⃣ <code>temp_intervalos</code> → factor con el <strong>intervalo
asignado a cada temperatura</strong>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">22.52</span>, <span class="fl">18.70</span>, <span class="fl">19.61</span>, <span class="fl">22.79</span>, <span class="fl">29.38</span>, <span class="fl">30.19</span>, <span class="fl">33.16</span>, <span class="fl">36.97</span>, <span class="fl">33.29</span>, <span class="fl">28.98</span>, <span class="fl">24.31</span>, <span class="fl">22.43</span>)</span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a><span class="co"># Agrupación en rangos definidos</span></span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a>temp_intervalos <span class="ot">&lt;-</span> <span class="fu">cut</span>(temp, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">50</span>))</span>
<span id="cb29-5"><a href="#cb29-5" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" tabindex="-1"></a><span class="co"># Mostramos los intervalos hechos</span></span>
<span id="cb29-7"><a href="#cb29-7" tabindex="-1"></a>temp_intervalos</span></code></pre></div>
<pre><code>##  [1] (20,30] (0,20]  (0,20]  (20,30] (20,30] (30,50] (30,50] (30,50] (30,50]
## [10] (20,30] (20,30] (20,30]
## Levels: (0,20] (20,30] (30,50]</code></pre>
</div>
<div id="aplicación-práctica-en-pediatría" class="section level3">
<h3>Aplicación práctica en Pediatría</h3>
<p>Podemos usar <code>aggregate()</code> para resumir datos numéricos
según los intervalos de edad creados.</p>
<ul>
<li><p><strong>Lectura de datos</strong><br />
Se carga el conjunto de datos <code>children.csv</code>, que contiene la
columna <code>edad</code> y varias variables numéricas (peso, altura,
talla, etc.).</p></li>
<li><p><strong>Agrupación por intervalos</strong><br />
Se crean intervalos de edad de 1 año (por ejemplo, de 5 a 19 años)
utilizando la función <code>cut()</code>. Cada niño queda asignado al
intervalo correspondiente según su edad.</p></li>
<li><p><strong>Cálculo de medias</strong><br />
Se calcula la media de cada variable numérica para cada intervalo de
edad con <code>aggregate()</code>, ignorando valores faltantes. Esto
genera un resumen donde cada fila representa un intervalo y cada columna
la media de una variable.</p></li>
<li><p><strong>Frecuencia de intervalos (opcional)</strong><br />
Se puede comprobar cuántos niños hay en cada intervalo para interpretar
correctamente las medias.</p></li>
</ul>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a>pediatria <span class="ot">&lt;-</span> <span class="fu">read.csv2</span>(<span class="st">&quot;children.csv&quot;</span>)</span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a><span class="co"># Creamos intervalos de edad de 1 en 1 año (de 5 a 19)</span></span>
<span id="cb31-4"><a href="#cb31-4" tabindex="-1"></a>edad_intervalos <span class="ot">&lt;-</span> <span class="fu">cut</span>(pediatria<span class="sc">$</span>edad, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">5</span>, <span class="dv">19</span>))</span>
<span id="cb31-5"><a href="#cb31-5" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" tabindex="-1"></a><span class="co"># Calculamos la media de todas las variables numéricas por cada grupo de edad</span></span>
<span id="cb31-7"><a href="#cb31-7" tabindex="-1"></a>resumen_edad <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(pediatria[, <span class="sc">-</span><span class="dv">1</span>], <span class="at">by =</span> <span class="fu">list</span>(<span class="at">edad =</span> edad_intervalos), </span>
<span id="cb31-8"><a href="#cb31-8" tabindex="-1"></a>                          <span class="at">FUN =</span> mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>edad_intervalos</span></code></pre></div>
<pre><code>##    [1] (5,6]   (5,6]   (5,6]   (5,6]   (5,6]   (5,6]   (5,6]   (5,6]   (6,7]  
##   [10] (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]  
##   [19] (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]  
##   [28] (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]  
##   [37] (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]  
##   [46] (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]  
##   [55] (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]   (6,7]  
##   [64] (6,7]   (6,7]   (6,7]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##   [73] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##   [82] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##   [91] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [100] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [109] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [118] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [127] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [136] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [145] (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]   (7,8]  
##  [154] (7,8]   (7,8]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [163] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [172] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [181] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [190] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [199] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [208] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [217] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [226] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [235] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [244] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [253] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [262] (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]   (8,9]  
##  [271] (8,9]   (8,9]   (8,9]   (8,9]   (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [280] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [289] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [298] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [307] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [316] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [325] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [334] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [343] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [352] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [361] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [370] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [379] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [388] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [397] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [406] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [415] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [424] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [433] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [442] (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10]  (9,10] 
##  [451] (9,10]  (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [460] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [469] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [478] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [487] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [496] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [505] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [514] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [523] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [532] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [541] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [550] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [559] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [568] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [577] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [586] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [595] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [604] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [613] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11] (10,11]
##  [622] (10,11] (10,11] (10,11] (10,11] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [631] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [640] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [649] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [658] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [667] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [676] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [685] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [694] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [703] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [712] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [721] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [730] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [739] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [748] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [757] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [766] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [775] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [784] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12]
##  [793] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (11,12] (12,13] (12,13]
##  [802] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [811] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [820] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [829] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [838] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [847] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [856] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [865] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [874] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [883] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [892] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [901] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [910] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [919] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [928] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [937] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [946] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [955] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [964] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [973] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [982] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
##  [991] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
## [1000] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13] (12,13]
## [1009] (12,13] (12,13] (12,13] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1018] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1027] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1036] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1045] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1054] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1063] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1072] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1081] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1090] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1099] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1108] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1117] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1126] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1135] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1144] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1153] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1162] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1171] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1180] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1189] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14] (13,14]
## [1198] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1207] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1216] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1225] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1234] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1243] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1252] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1261] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1270] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1279] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1288] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1297] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1306] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1315] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1324] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1333] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1342] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1351] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1360] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1369] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1378] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1387] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1396] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1405] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1414] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1423] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1432] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1441] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1450] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1459] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1468] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1477] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15] (14,15]
## [1486] (14,15] (14,15] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1495] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1504] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1513] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1522] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1531] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1540] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1549] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1558] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1567] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1576] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1585] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1594] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1603] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1612] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1621] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1630] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1639] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1648] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1657] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1666] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1675] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1684] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1693] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1702] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1711] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1720] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1729] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1738] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1747] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1756] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1765] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1774] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1783] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1792] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16]
## [1801] (15,16] (15,16] (15,16] (15,16] (15,16] (15,16] (16,17] (16,17] (16,17]
## [1810] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1819] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1828] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1837] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1846] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1855] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1864] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1873] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1882] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1891] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1900] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1909] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1918] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1927] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1936] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1945] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1954] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1963] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1972] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1981] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1990] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [1999] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2008] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2017] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2026] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2035] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2044] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2053] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2062] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2071] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2080] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17] (16,17]
## [2089] (16,17] (16,17] (16,17] (16,17] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2098] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2107] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2116] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2125] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2134] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2143] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2152] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2161] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2170] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2179] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2188] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2197] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2206] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2215] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2224] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2233] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2242] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18] (17,18]
## [2251] (17,18] (17,18] (17,18] (17,18] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2260] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2269] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2278] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2287] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2296] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2305] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2314] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2323] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2332] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19] (18,19]
## [2341] (18,19] (18,19] (18,19] (18,19] (18,19]
## 14 Levels: (5,6] (6,7] (7,8] (8,9] (9,10] (10,11] (11,12] (12,13] ... (18,19]</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>resumen_edad</span></code></pre></div>
<pre><code>##       edad      edad     peso    talla
## 1    (5,6]  5.707500 21.50000 118.9500
## 2    (6,7]  6.649310 23.40517 120.3414
## 3    (7,8]  7.492360 24.87079 124.8000
## 4    (8,9]  8.543613 28.49580 130.4160
## 5   (9,10]  9.592599 31.19548 135.5582
## 6  (10,11] 10.542931 36.39655 141.4655
## 7  (11,12] 11.556667 38.43103 145.1511
## 8  (12,13] 12.535377 43.94198 151.9792
## 9  (13,14] 13.578763 49.93280 157.4968
## 10 (14,15] 14.602862 54.59138 162.5007
## 11 (15,16] 15.501473 57.51411 165.1204
## 12 (16,17] 16.511189 59.91294 167.2969
## 13 (17,18] 17.505679 61.77654 167.1420
## 14 (18,19] 18.438681 62.06264 167.5692</code></pre>
<pre><code>
---

### Cambios clave realizados:
* **Claridad Terminológica:** He añadido la notación estándar ($n_i, N_i, f_i, F_i$) para que el código sea académicamente riguroso.
* **Estructura:** Se ha separado el código en bloques lógicos, facilitando la ejecución paso a paso.
* **Legibilidad:** He renombrado variables (como `temp2` a `temp_intervalos`) para que el código sea &quot;autodocumentado&quot;.
* **Buenas prácticas:** Se ha incluido `na.rm = TRUE` en el ejemplo de `aggregate`, que es esencial para que el código no falle si faltan datos en el dataset de pediatría.
</code></pre>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
